### ISSUE TITLE
Aria2 Status "Not Connected" and "Error Authorization Failed!"

### ISSUE THREAD

**Issue by vanshyp** [iranee/readynas-aria2#1]
I installed the add-on and I am getting Aria2 Status "Not Connected" and constant popups "Error Authorization Failed!".
I thought maybe the issue had to do with setting the RPC secret token but it hasn't changed anything for me.
Using the latest firmware 6.9.1 on a legacy ReadyNAS Ultra 4.

**Comment by iranee** [comment]
you can From [More Info] get The RPC
